### ISSUE TITLE
Improve information about how to run the test

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-sensorml20#3]
We should have two options:

1) Provide a URL
2) Upload file to be tested

For the first option we should clarify that the URL can be

an SOS 2.0 DescribeSensor request (The root element is ...). For example
an SOS 1.0 DescribeSensor request (The root element is ...) , For example
a SensorML with a public URL ( The root element is ...). For example ( Maybe an example from the GitHub repository)
For the second option, in similar way clarify what type of files can be submitted.

Also we need to provide some examples. What is the URL for the reference implementation?

**Comment by rockygis** [comment]
I have updated example to GitHub, which look like below:
But I cannot get the url to SOS 1.0 or 2.0.
The SOS Service of 52north don't support sensorML 2.0 in the DescribeSensor Operation.

![image](https://cloud.githubusercontent.com/assets/6157282/6723763/90145f0c-ce27-11e4-8fb0-e923c9696b6a.png)

SensorML URL Example:

a SensorML with a public URL ( The root element is "sml:SensorML"). 
For example:
https://raw.githubusercontent.com/opengeospatial/ets-sensorml20/master/src/main/example/SensorML2_1.xml
https://raw.githubusercontent.com/opengeospatial/ets-sensorml20/master/src/main/example/SensorML2_2.xml
