### ISSUE TITLE
Add conformance class configuration into the sensorml20 test. 

### ISSUE THREAD

**Issue by keshavnangare** [opengeospatial/ets-sensorml20#33]
The test needs to be updated to better provide information about the grouping of the conformance class and determination about which ones are the basic conformance classes needed for certification.

Changes that are required are described here:

https://github.com/opengeospatial/cite/wiki/Encoding-Conformance-Classes

**Comment by epicureanism** [comment]
Conformance class name was specified in the config file.
https://github.com/opengeospatial/ets-sensorml20/blob/838a4085d8fa8b817be174a07d737f7ad0081202/src/main/config/config.xml
