### ISSUE TITLE
Review current status of test suite

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-sensorml20#37]
Please check the following:
* Test suite can be run with TEAM Engine (technical check).
* Test suite is complete (check of specification).

**Comment by ghobona** [comment]
@arieslai To check whether the requirement 14 test supports "http" at [Line 130](https://github.com/opengeospatial/ets-sensorml20/blob/master/src/main/java/org/opengis/cite/sensorml20/level1/CoreAbstractProcess.java#L130)

**Comment by ghobona** [comment]
@arieslai To extend the [test](https://github.com/opengeospatial/ets-sensorml20/blob/master/src/main/java/org/opengis/cite/sensorml20/level1/CoreAbstractProcess.java#L139) for Requirement 15 to support the rest of the requirement "The complete description of that process is thus the addition of information from both process descriptions".

**Comment by ghobona** [comment]
Agreement with @arieslai @dstenger during 2020-05-20 call that the test for Req 16 (A.2.11) is fine.

**Comment by ghobona** [comment]
Next steps for @arieslai : Prepare for release

**Comment by arieslai** [comment]
#### Prepare release (for each test suite individually)

- [ ] The master branch should contain the latest "stable" version. Make sure all verified pull requests are merged.
- [ ] Make sure it builds properly running `mvn clean install site -Pintegration-tests,docker`.
- [ ] Test locally the master branch with the [reference implementation](https://github.com/opengeospatial/cite/wiki/Reference-Implementations), if there is one.
	- If it is OK, continue, if not create or update an issue, in the issue tracker of that test.
- [ ] Review closed issues to be included in the release. 
	- Update title if appropriate.
	- Tag, if they are not tagged with the milestone number.
- [ ] Update release notes, usually the file is at src/site/markdown/relnotes.md.
	- Add a new title for the revision, if there is not one already.
	- Copy the issues to be included in the release, link and title.
	- Add any other highlights.
- [ ] Create a new issue in the [OGC release tracker](https://github.com/opengeospatial/te-releases/issues) and set label `approved-by-test-lead`.
	- Write a title for the issue should containing: [Abbreviation] [version] revision [revision] in *Beta*. For example: WFS 1.1 revision 1.23 in Beta. It should always be in Beta. OGC staff will create the issue related to making the releases in the production, official web site.

**Comment by dstenger** [comment]
Release was prepared: https://github.com/opengeospatial/te-releases/issues/305
