### ISSUE TITLE
Create unit tests for each test

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-sensorml20#38]
Currently, there are no unit tests implemented: https://github.com/opengeospatial/ets-sensorml20/tree/master/src/test/java/org/opengis/cite/sensorml20/level1

**Comment by ghobona** [comment]
Update on 2020-07-15 @arieslai has  created the unit test and demonstrated to @ghobona today.

Agreement that @arieslai will create a pull request and @ghobona will review.

**Comment by arieslai** [comment]
Dear @ghobona ,

The pull request is made, thank you.
https://github.com/opengeospatial/ets-sensorml20/pull/49
