### ISSUE TITLE
Minor typo in AssertionError message of AggregateProcessSchema.PropertyConnectionrestrictions()

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ets-sensorml20#41]
'impit' should be 'input'.

https://github.com/opengeospatial/ets-sensorml20/blob/master/src/main/java/org/opengis/cite/sensorml20/level2/AggregateProcessSchema.java#L346

**Comment by arieslai** [comment]
Fixed in commit [#69b1328](https://github.com/opengeospatial/ets-sensorml20/commit/645a23dcf875b8b448253f212fcc5995ad5a9137#diff-62f130ea4cd29a6c7c56a26e3de9ddd9)
