### ISSUE TITLE
Minor typos in PhysicalComponent.ByPointOrLocation() method

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ets-sensorml20#42]
https://github.com/opengeospatial/ets-sensorml20/blob/master/src/main/java/org/opengis/cite/sensorml20/level1/PhysicalComponent.java#L53

"position element shall defind content" **should be** "position element shall define content"

https://github.com/opengeospatial/ets-sensorml20/blob/master/src/main/java/org/opengis/cite/sensorml20/level1/PhysicalComponent.java#L58

"location or point does not define" **should be** "location or point is not defined"

**Comment by arieslai** [comment]
Fixed in commit [#69b1328](https://github.com/opengeospatial/ets-sensorml20/commit/645a23dcf875b8b448253f212fcc5995ad5a9137#diff-23848f699c7ab61a869225710b6ec5c4)
