### ISSUE TITLE
Remove PhysicalSystem from Line 71 of CoreConcepts class

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ets-sensorml20#43]
`PhysicalSystem.components` has a minOccurs of zero in the [schema](http://schemas.opengis.net/sensorML/2.0/physical_system.xsd) and the specification document does not require it to be added to a `PhysicalSystem` element.

[Line 71](https://github.com/opengeospatial/ets-sensorml20/blob/master/src/main/java/org/opengis/cite/sensorml20/level1/CoreConcepts.java#L71) of the `CoreConcepts` class should therefore not include `PhysicalSystem`.

**Comment by arieslai** [comment]
Fixed in commit [#69b1328](https://github.com/opengeospatial/ets-sensorml20/commit/645a23dcf875b8b448253f212fcc5995ad5a9137#diff-9b6b986639413704da902340a1b96c2b)
