### ISSUE TITLE
Replace item.getNodeValue() with item.getTextContent() on Line 107 of CoreConcepts

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ets-sensorml20#44]
getNodeValue() fails when there is a codeSpace in the element. Replace item.getNodeValue() with item.getTextContent() on [Line 107](https://github.com/opengeospatial/ets-sensorml20/blob/master/src/main/java/org/opengis/cite/sensorml20/level1/CoreConcepts.java#L107) of the CoreConcepts class.

**Comment by arieslai** [comment]
Fixed in commit [#69b1328](https://github.com/opengeospatial/ets-sensorml20/blob/master/src/main/java/org/opengis/cite/sensorml20/level1/CoreConcepts.java#L107)
