### ISSUE TITLE
Revise the test for Requirement 4 to be consistent with Core Metadata listed in Section 7.2.2

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ets-sensorml20#45]
Requirement 4 says "The core model for a process shall include metadata that support identification, discovery, and qualification of the process."

The only place in the specification where the metadata that support identification, discovery, and qualification are listed is in Section 7.2.2 which says "The DescribedObject includes several descriptive properties that support rapid discovery (keywords, identification, and classification), constraints (validTime, securityConstraints, legalConstraints), qualification (characteristics and capabilities), references (contacts and documentation), and history."

Therefore, [CoreConcepts.CoreConcepsMetadata()](https://github.com/opengeospatial/ets-sensorml20/blob/master/src/main/java/org/opengis/cite/sensorml20/level1/CoreConcepts.java#L121) should be updated to run three checks:

* check whether sml:identification is included. 
* check whether sml:keywords **or** sml:classification are included.  [i.e. the discovery group]
* check whether sml:characteristics **or** sml:capabilities are included. [i.e. the qualification group]

For example, a SensorML document that includes sml:identification, sml:keywords and sml:capabilities would **PASS**

**Comment by arieslai** [comment]
Fixed in commit [#69b1328](https://github.com/opengeospatial/ets-sensorml20/blob/master/src/main/java/org/opengis/cite/sensorml20/level1/CoreConcepts.java#L121)

**Comment by ghobona** [comment]
Fixed in commit https://github.com/opengeospatial/ets-sensorml20/commit/645a23dcf875b8b448253f212fcc5995ad5a9137#diff-9b6b986639413704da902340a1b96c2bR120
