### ISSUE TITLE
Req 49 test cannot be run automatically

### ISSUE THREAD

**Issue by arieslai** [opengeospatial/ets-sensorml20#46]
B.1.5 The value of the definition attribute is a resolvable URI (Req 49) is added in [CoreAbstractProcessSchema.ExtensionProcessExecution()](https://github.com/opengeospatial/ets-sensorml20/blob/master/src/main/java/org/opengis/cite/sensorml20/level2/CoreAbstractProcessSchema.java#L112)

**Comment by dstenger** [comment]
https://github.com/opengeospatial/ets-sensorml20/commit/645a23dcf875b8b448253f212fcc5995ad5a9137

**Comment by ghobona** [comment]
Agreed with @arieslai and @dstenger to remove the contents of the test for Requirement 49 and to replace with a comment that "This test cannot be run automatically".

**Comment by arieslai** [comment]
Fixed in [#fc9f730](https://github.com/opengeospatial/ets-sensorml20/commit/fc9f73087a51cebf835eb4689dbbf08691a6edf3).
