### ISSUE TITLE
Req 54 added in commit #69b1328

### ISSUE THREAD

**Issue by arieslai** [opengeospatial/ets-sensorml20#47]
B.1.10 Extension element used for security tagging of individual properties  (Req 54) is added in [CoreAbstractProcessSchema.IndividualSecurityTags()](https://github.com/opengeospatial/ets-sensorml20/blob/master/src/main/java/org/opengis/cite/sensorml20/level2/CoreAbstractProcessSchema.java#L244)

**Comment by dstenger** [comment]
https://github.com/opengeospatial/ets-sensorml20/commit/645a23dcf875b8b448253f212fcc5995ad5a9137

**Comment by ghobona** [comment]
@ghobona To look for examples and provide @arieslai with more information.

**Comment by ghobona** [comment]
@arieslai 

I have uploaded an example to https://github.com/opengeospatial/ets-sensorml20/blob/master/src/test/resources/OEM_Sensor_SecurityConstraints.xml

**Comment by arieslai** [comment]
Hi @ghobona,
Thank you for providing me the great example. I have tested the example and modified Req 49(#46), Req 54(#47), also made a bug fixed of Req 53.

Fixed in [#fc9f730](https://github.com/opengeospatial/ets-sensorml20/commit/fc9f73087a51cebf835eb4689dbbf08691a6edf3).
